module.exports = {
  caseType:'authenticated_device_operation', initialState:'requested',
  states:['requested','identity_verified','provisioned','telemetry_validated','anomaly_review','maintenance_approved','maintenance_complete','outcome_recorded'],
  createRoles:['fleet_admin','operator'],
  evidenceKinds:['csr_digest','certificate_reference','firmware_manifest','telemetry_batch_digest','clock_gap_report','anomaly_manifest','maintenance_order','operator_outcome'],
  requiredSignals:['deviceIdentityVerified','firmwareVersion','schemaVersion','unitSet','sequenceGapCount','latencyMs','policyVersion'],
  assessmentRoles:['pki_admin','fleet_admin','operator','maintenance_manager'],
  auditRoles:['fleet_admin','operator','maintenance_manager'],
  connectorRoles:['pki_admin','fleet_admin','operator'],
  professionalBoundary:'All results are advisory; this service cannot issue device control or firmware commands and requires an authorized operator.',
  connectors:[
    {name:'device_registry_pki',purpose:'device identity and certificate references'},
    {name:'gateway_broker',purpose:'versioned telemetry batch receipts'},
    {name:'time_series_store',purpose:'durable telemetry references'},
    {name:'cmms',purpose:'maintenance work-order exchange'},
    {name:'edge_deployment',purpose:'approved manifest receipts only'},
    {name:'alerting',purpose:'operator notification receipts'},
  ],
  transitions:[
    {from:'requested',action:'verify_identity',to:'identity_verified',roles:['pki_admin'],requiresEvidence:true},
    {from:'identity_verified',action:'provision',to:'provisioned',roles:['fleet_admin'],requiresEvidence:true,dualControl:true},
    {from:'provisioned',action:'validate_telemetry',to:'telemetry_validated',roles:['operator'],requiresEvidence:true},
    {from:'telemetry_validated',action:'route_anomaly',to:'anomaly_review',roles:['operator'],requiresEvidence:true},
    {from:'anomaly_review',action:'approve_maintenance',to:'maintenance_approved',roles:['maintenance_manager'],requiresEvidence:true,dualControl:true},
    {from:'maintenance_approved',action:'complete_maintenance',to:'maintenance_complete',roles:['technician'],requiresEvidence:true},
    {from:'maintenance_complete',action:'record_outcome',to:'outcome_recorded',roles:['operator'],requiresEvidence:true,dualControl:true},
  ],
  assess:x=>{const gaps=Number(x.sequenceGapCount);const latency=Number(x.latencyMs);const valid=Number.isSafeInteger(gaps)&&gaps>=0&&Number.isFinite(latency)&&latency>=0;return{disposition:!valid||!x.deviceIdentityVerified||gaps>0?'quarantine_or_manual_review':'eligible_for_operator_anomaly_review',controlCommand:null,telemetry:{firmware:x.firmwareVersion,schema:x.schemaVersion,units:x.unitSet,latencyMs:latency}};},
};
